homeassistant:
  packages: !include_dir_named packages/
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.156.0/24
        - 10.1.30.0/24
      trusted_users:
        192.168.156.216: 7fda7b6f10f741bbaeaf0e6ce1a0908a



lovelace:
  mode: yaml
  resources: !include_dir_merge_list lovelace/resources
  dashboards:
    my-theme:
      mode: yaml
      title: My Theme
      icon: mdi:alpha-m-box
      show_in_sidebar: true
      filename: ui-lovelace.yaml
      require_admin: false

    my-dashboard:
      mode: yaml
      title: Tablete
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      filename: ui-dashboard.yaml
      require_admin: false


frontend:
  themes: !include_dir_merge_named themes


browser_mod:
  prefix: "browser_"
  devices:
    8c4dd22e_ef196e36:
      name: tablet
      camera: true

    eac8cb7d-f29085f2:
      name: niklas_mbp_safari
      disable:
        - light
        - media_player
        - sensor
    0c46f0e8_e1aad3f4:
      name: niklas_mbp_chrome
      disable:
        - light
        - media_player
        - sensor

    b9d4a2a1_f3829503:
      name: Niklas iPhone
      disable:
        - light
        - media_player
        - sensor

    fa9f4114_6fa501c2:
      name: Hanna iPhone
      disable:
        - light
        - media_player
        - sensor


hassio:
cloud:
map:
person:
config:
updater:
sun:
system_health:
mobile_app:
ios:
#python_script:


#frontend:
#  themes: !include_dir_merge_named themes

ssdp:
zeroconf:

#breaking_changes:

hacs:
  token: !secret hacs

#rfxtrx:
#  device: !secret rfxtrx

ifttt:
  key: !secret ifttt

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

vacuum:
  - platform: xiaomi_miio
    host: 192.168.156.4
    name: Wowite
    token: !secret vacuum_token

fan:
  - platform: xiaomi_miio_fan
    name: sovrum
    host: 192.168.156.235
    token: !secret fan_sovrum

  - platform: xiaomi_miio_fan
    name: vardagsrum
    host: 192.168.156.154
    token: !secret fan_vardagsrum

  - platform: xiaomi_miio
    name: Mi Air Purifier 2H
    host: 192.168.156.222
    token: !secret air_purifyer


recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml
notify: !include notify.yaml

group: !include entities/group.yaml
device_tracker: !include entities/device_tracker.yaml
light: !include entities/light.yaml
switch: !include entities/switch.yaml
#script: !include scripts.yaml
script: !include_dir_merge_named scripts
sensor: !include entities/sensor.yaml
binary_sensor: !include entities/binary_sensor.yaml
input_boolean: !include entities/input_boolean.yaml
input_select: !include entities/input_select.yaml
