
custom_header:
  !include lovelace/mobil/custom_header/configuration.yaml

button_card_templates:
  !include_dir_merge_named lovelace/mobil/templates/button-card

views:
  !include_dir_merge_list lovelace/mobil/views
