compact_mode: true
hide_unused: true
hide_config: true
hide_raw: true
hide_help: true
hidden_tab_redirect: false
background: '#324d67'
shadow: false
exceptions:
  - conditions:
  - conditions:
      user_agent: Mobile
    config:
      footer_mode: false
      disable_sidebar: false
      menu_hide: true
      chevrons: false
      indicator_top: true

  - conditions:
      user_agent: Home Assistant
    config:
      footer_mode: false
      disable_sidebar: false
      menu_hide: true
      chevrons: false
      indicator_top: true


  - conditions:
      user_agent: Android
    config:
      footer_mode: false
      disable_sidebar: true
      menu_hide: true
      chevrons: false
      indicator_top: true
      kiosk_mode: false
