
##################################################
## Component
##################################################

alarm_control_panel:
  - platform: manual
    name: House
    pending_time: 10
    trigger_time: 45
    disarm_after_trigger: false
    armed_home:
      pending_time: 0
      delay_time: 30


##################################################
## Sensors
##################################################


sensor:
  - platform: template
    sensors:
      frontdoor:
        friendly_name: 'Ytterdörren'
        value_template: '{% if is_state("binary_sensor.frontdoor", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.frontdoor", "on") %}mdi:door-open{% else %}mdi:door-closed{% endif %}'
        entity_id: binary_sensor.frontdoor
      backdoor:
        friendly_name: 'Altandörren'
        value_template: '{% if is_state("binary_sensor.backdoor", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.backdoor", "on") %}mdi:door-open{% else %}mdi:door-closed{% endif %}'
        entity_id: binary_sensor.backdoor
      beedrom_window:
        friendly_name: 'Sovrumsfönstret'
        value_template: '{% if is_state("binary_sensor.sovrums_fonstret", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.sovrums_fonstret", "on") %}mdi:window-open{% else %}mdi:window-closed{% endif %}'
        entity_id: binary_sensor.sovrums_fonstret

      office_window:
        friendly_name: 'Kontorsfönstret'
        value_template: '{% if is_state("binary_sensor.kontoret_fonster", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.kontoret_fonster", "on") %}mdi:window-open{% else %}mdi:window-closed{% endif %}'
        entity_id: binary_sensor.kontoret_fonster

      albins_window:
        friendly_name: 'Fönster Albins rum'
        value_template: '{% if is_state("binary_sensor.albins_fonster", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.albins_fonster", "on") %}mdi:window-open{% else %}mdi:window-closed{% endif %}'
        entity_id: binary_sensor.albins_fonster


      kitchen_window:
        friendly_name: 'Köksfönstret'
        value_template: '{% if is_state("binary_sensor.kok_fonster", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.kok_fonster", "on") %}mdi:window-open{% else %}mdi:window-closed{% endif %}'
        entity_id: binary_sensor.kok_fonster

#      kitchen_small_window:
#        friendly_name: 'Lilla köksfönstret'
#        value_template: '{% if is_state("binary_sensor.kok_lilla_fonster", "on") %}Öppet{% else %}Stängt{% endif %}'
#        icon_template: '{% if is_state("binary_sensor.kok_lilla_fonster", "on") %}mdi:window-open{% else %}mdi:window-closed{% endif %}'
#        entity_id: binary_sensor.kok_lilla_fonster

      livingroom_window:
        friendly_name: 'Vardagsrumsfönstret'
        value_template: '{% if is_state("binary_sensor.vardagsrummet_fonster", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.vardagsrummet_fonster", "on") %}mdi:window-open{% else %}mdi:window-closed{% endif %}'
        entity_id: binary_sensor.vardagsrummet_fonster



      all_doors_check:
        value_template: >-
          {{ is_state('binary_sensor.frontdoor', 'off')
             and is_state('binary_sensor.backdoor', 'off')
             and is_state('binary_sensor.sovrums_fonstret', 'off')
             and is_state('binary_sensor.kontoret_fonster', 'off')
             and is_state('binary_sensor.albins_fonster', 'off')
             and is_state('binary_sensor.kok_fonster', 'off')
             and is_state('binary_sensor.vardagsrummet_fonster', 'off') }}
        friendly_name: 'Alla Dörrar och Fönster'
        entity_id:
          - sensor.frontdoor
          - sensor.backdoor
          - sensor.beedrom_window
          - sensor.office_window
          - sensor.albins_window
          - sensor.kitchen_window
          - sensor.livingroom_window
          - sensor.time




      all_doors_status:
        value_template: '{% if states.sensor.all_doors_check %}
          {% if states.sensor.all_doors_check.state == "False" %}

          {% else %}
            Stängda
          {% endif %}
          {% else %}
            Öppna
          {% endif %}'
        friendly_name: 'Dörrar & Fönster'
        entity_id:
          - sensor.frontdoor
          - sensor.backdoor
          - sensor.beedrom_window
          - sensor.office_window
          - sensor.albins_window
          - sensor.kitchen_window
          - sensor.kitchen_small_window
          - sensor.livingroom_window
          - sensor.time



      larm:
        friendly_name: 'Larmet'
        entity_id: alarm_control_panel.house
        value_template: >-
          {%- if is_state("alarm_control_panel.house", "disarmed") %}
              Frånkopplat
          {% elif is_state("alarm_control_panel.house", "pending") %}
              väntar
          {% elif is_state("alarm_control_panel.house", "armed_away") %}
              Tillkopplat
          {% elif is_state("alarm_control_panel.house", "armed_home") %}
              Skalskydd
          {% else %}
              failed
          {%- endif %}


      arlo:
        friendly_name: 'Arlo'
        entity_id: alarm_control_panel.aarlo_arlo
        value_template: >-
          {%- if is_state("alarm_control_panel.aarlo_arlo", "disarmed") %}
              Frånkopplat
          {% elif is_state("alarm_control_panel.aarlo_arlo", "pending") %}
              väntar
          {% elif is_state("alarm_control_panel.aarlo_arlo", "armed_away") %}
              Tillkopplat
          {% elif is_state("alarm_control_panel.aarlo_arlo", "armed_home") %}
              Skalskydd
          {% else %}
              failed
          {%- endif %}



##################################################
## Scripts
##################################################


script:
  jarvis_skalskydd:
    alias: jarvis_skalskydd
    sequence:
      - service: notify.alla
        data_template:
          message: >
            Skalskyddet på kl {{ states.sensor.time.state }}

            {% for state in states.sensor | selectattr('state', 'equalto', 'Öppet')%}
            {%- if loop.first %}VARNING! {% elif loop.last %}, {% else %}, {% endif -%}
            {{ state.name | lower }}
            {%- endfor %}


  jarvis_larm:
    alias: jarvis_larm
    sequence:
      - service: notify.alla
        data_template:
          message: >
            Larmet på kl {{ states.sensor.time.state }}

            {% for state in states.sensor | selectattr('state', 'equalto', 'Öppet')%}
            {%- if loop.first %}VARNING! {% elif loop.last %}, {% else %}, {% endif -%}
            {{ state.name | lower }}
            {%- endfor %}

  unlock:
      alias: "Unlock frontdoor"
      sequence:
        - service: notify.ios_niklas_iphone_8
          data:
            message: 'Larm av kl {{now().strftime("%H:%M")}}'
            data:
              url: "shortcuts://run-shortcut?name=unlock"
              push:
                badge: 0
              attachment:
                url: ""
                content-type: jpg
                hide-thumbnail: false

        - service: notify.ios_hannas_iphone
          data:
            message: 'Larm av kl {{now().strftime("%H:%M")}}'
            data:
              url: "shortcuts://run-shortcut?name=unlock"
              push:
                badge: 0
              attachment:
                url: ""
                content-type: jpg
                hide-thumbnail: false



##################################################
## Alerts
##################################################

alert:
  front_door:
    name: Ytterdörren är öppen
    done_message: Ytterdörren har stängts!
    entity_id: binary_sensor.frontdoor
    state: 'on'
    repeat: 2
    can_acknowledge: True
    skip_first: True
    notifiers:
      - notify.mobile_app_niklas_iphone_8
      - notify.mobile_app_hannas_iphone
      - slack
