
##################################################
## Component
##################################################

alarm_control_panel:
  - platform: manual
    name: House
    arming_time: 60
    trigger_time: 45
    disarm_after_trigger: false
    armed_home:
      arming_time: 0
      delay_time: 30


##################################################
## Sensors
##################################################


sensor:
  - platform: template
    sensors:
#      frontdoor:
#        friendly_name: 'Ytterdörren'
#        value_template: '{% if is_state("binary_sensor.frontdoor", "on") %}Öppet{% else %}Stängt{% endif %}'
#        icon_template: '{% if is_state("binary_sensor.frontdoor", "on") %}mdi:door-open{% else %}mdi:door-closed{% endif %}'
#        entity_id: binary_sensor.frontdoor
      backdoor:
        friendly_name: 'Balkongdörren'
        value_template: '{% if is_state("binary_sensor.backdoor", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.backdoor", "on") %}mdi:door-open{% else %}mdi:door-closed{% endif %}'
        entity_id: binary_sensor.backdoor

      franska_balkongen:
        friendly_name: 'Franska balkongen'
        value_template: '{% if is_state("binary_sensor.franska_balkongen", "on") %}Öppet{% else %}Stängt{% endif %}'
        icon_template: '{% if is_state("binary_sensor.franska_balkongen", "on") %}mdi:window-open{% else %}mdi:window-closed{% endif %}'
        entity_id: binary_sensor.franska_balkongen








#      larm:
#        friendly_name: 'Larmet'
#        entity_id: alarm_control_panel.house
#        value_template: >-
#          {%- if is_state("alarm_control_panel.house", "disarmed") %}
#              Frånkopplat
#          {% elif is_state("alarm_control_panel.house", "pending") %}
#              väntar
#          {% elif is_state("alarm_control_panel.house", "armed_away") %}
#              Tillkopplat
#          {% elif is_state("alarm_control_panel.house", "armed_home") %}
#              Skalskydd
#          {% else %}
#              failed
#          {%- endif %}


#      arlo:
#        friendly_name: 'Arlo'
#        entity_id: alarm_control_panel.aarlo_arlo
#        value_template: >-
#          {%- if is_state("alarm_control_panel.aarlo_arlo", "disarmed") %}
#              Frånkopplat
#          {% elif is_state("alarm_control_panel.aarlo_arlo", "pending") %}
#              väntar
#          {% elif is_state("alarm_control_panel.aarlo_arlo", "armed_away") %}
#              Tillkopplat
#          {% elif is_state("alarm_control_panel.aarlo_arlo", "armed_home") %}
#              Skalskydd
#          {% else %}
#              failed
#          {%- endif %}



##################################################
## Scripts
##################################################


script:
  jarvis_skalskydd:
    alias: jarvis_skalskydd
    sequence:
      - service: notify.alla
        data_template:
          message: >
            Skalskyddet på kl {{ states.sensor.time.state }}

            {% for state in states.sensor | selectattr('state', 'equalto', 'Öppet')%}
            {%- if loop.first %}VARNING! {% elif loop.last %}, {% else %}, {% endif -%}
            {{ state.name | lower }}
            {%- endfor %}


  jarvis_larm:
    alias: jarvis_larm
    sequence:
      - service: notify.alla
        data_template:
          message: >
            Larmet på kl {{ states.sensor.time.state }}

            {% for state in states.sensor | selectattr('state', 'equalto', 'Öppet')%}
            {%- if loop.first %}VARNING! {% elif loop.last %}, {% else %}, {% endif -%}
            {{ state.name | lower }}
            {%- endfor %}
