

aarlo:
  username: !secret arlo_username
  password: !secret arlo_passwd
#  reconnect_every: 70


camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: aarlo
    home_mode_name: baksidan
    away_mode_name: armed


binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding

sensor:
  - platform: aarlo
    monitored_conditions:
    - last_capture
    - total_cameras
    - battery_level
    - captured_today
    - signal_strength

  - platform: template
    sensors:
      servicemode_msg:
        friendly_name: 'Servicemode message'
        value_template: "{{ states.calendar.niklasvilnerssongmailcom.attributes.message }}"
        entity_id: calendar.niklasvilnerssongmailcom
