


##################################################
##
## Sensors
##
##################################################

sensor:
  - platform: vasttrafik
    key: !secret vasttrafik_key
    secret: !secret vasttrafik_secret
    departures:
      - name: Linje 52
        from: Korsvägen
        heading: Linnéplatsen
        lines:
          - 52


  - platform: waze_travel_time
    name: waze_hem_marmorvagen
    origin: 57.698551, 11.98511
    destination: 57.647173, 12.118157
    region: 'EU'

  - platform: waze_travel_time
    name: waze_hem_thorne
    origin: 57.698551, 11.98511
    destination: 57.703054, 12.436605
    region: 'EU'

  - platform: waze_travel_time
    name: waze_hem_grastorp
    origin: 57.698551, 11.98511
    destination: 58.333225, 12.680733
    region: 'EU'
