##################################################
## Customize
##################################################

#homeassistant:
#  customize:
#    sensor.inside_filtered_realistic_temperature:
#      friendly_name: Inomhus
#      icon: mdi:thermometer
#    sensor.outside_filtered_realistic_temperature:
#      friendly_name: Utomhus
#      icon: mdi:thermometer


##################################################
## Sensors
##################################################


sensor:
  - platform: filter
    name: "Outside filtered realistic temperature"
    entity_id: sensor.temp_ute
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: 00:05
        precision: 2


  - platform: filter
    name: "Inside filtered realistic temperature"
    entity_id: sensor.temp_inne
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: 00:05
        precision: 2


  - platform: template
    sensors:
      temp_inne_filtrerad:
        friendly_name: "Inomhus"
        value_template: "{{ states.sensor.inside_filtered_realistic_temperature.state | round(1) }}"
        unit_of_measurement: '°C'
        icon_template: mdi:thermometer
        entity_id: sensor.inside_filtered_realistic_temperature


  - platform: template
    sensors:
      temp_ute_filtrerad:
        friendly_name: "Utomhus"
        value_template: "{{ states.sensor.outside_filtered_realistic_temperature.state | round(1) }}"
        unit_of_measurement: '°C'
        icon_template: mdi:thermometer
        entity_id: sensor.outside_filtered_realistic_temperature



##################################################
## Automations
##################################################
