sensor:
  - platform: krisinformation
    name: Krisinformation
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 50


automation:
  - alias: 'Krisinformation Alert'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:  sensor.krisinformation
        to: "Alert"
    action:
      - service: notify.alla
        data_template:
          message: >
            {{states.sensor.krisinformation.attributes.messages[0].Headline}} - {{states.sensor.krisinformation.attributes.messages[0].Message}} {{states.sensor.krisinformation.attributes.messages[0].Web}}
