
sensor:
  - platform: miflora
    mac: 'C4:7C:8D:64:32:13'
    name: Flower
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery

plant:
  tomaten:
    sensors:
      moisture: sensor.flower_moisture
      temperature: sensor.flower_temperature
      conductivity: sensor.flower_conductivity
      brightness: sensor.flower_light_intensity
      battery: sensor.flower_battery
    max_moisture: 65
    min_moisture: 20
    max_conductivity: 2000
    min_conductivity: 350
    min_temperature: 10
    max_temperature: 32
    max_brightness: 130000
