feedreader:
  urls:
    - https://www.shazbat.tv/rss/followed?passkey=4b98807cd97e4ccd6b89f4541880cfb50f34a078
    - https://hasspodcast.io/feed/podcast

automation:
  - alias: Send notification of RSS feed title when updated
    trigger:
      platform: event
      event_type: feedreader

    action:
      - service: notify.niklas
        data_template:
          title: "New RSS Item available"
          message: "New RSS Item - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }} {{trigger.event.data.title}}"
          data:
            url: "{{trigger.event.data.link}}"

      - service: persistent_notification.create
        data_template:
          title: "{{trigger.event.data.title}}"
          message: "New RSS item available - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
          notification_id: "update_available"
