


input_select:
  vacuum_mode:
    name: Ska Wowite städa idag?
    options:
     - 'Ja'
     - 'Nej'
    initial: 'Ja'
    icon: mdi:robot-vacuum

  vacuum_zone:
    name: 'Zone städning:'
    options:
      - 'Välj rum'
      - 'Hela lägenheten'
      - 'Albins rum'
      - 'Köket'
      - 'Vardagsrummet'
      - 'Sovrummet'
      - 'Hallen'
      - 'Stora hallen'
      - 'Kontoret'
    initial: 'Välj rum'
    icon: mdi:map-outline



sensor:
  - platform: template
    sensors:
      vacuum_time:
        friendly_name: "Städningstid"
        entity_id: vacuum.wowite
        unit_of_measurement: 'minuter'
        value_template: "{{ states.vacuum.wowite.attributes.cleaning_time }}"

  - platform: template
    sensors:
      vacuum_count:
        friendly_name: "Städningar"
        entity_id: vacuum.wowite
        unit_of_measurement: 'st'
        value_template: "{{ states.vacuum.wowite.attributes.cleaning_count }}"

  - platform: template
    sensors:
      vacuum_area:
        friendly_name: "Städningsyta"
        entity_id: vacuum.wowite
        unit_of_measurement: 'm²'
        value_template: "{{ states.vacuum.wowite.attributes.cleaned_area }}"

  - platform: template
    sensors:
      vacuum_main_brush:
        friendly_name: "Huvudborste"
        entity_id: vacuum.wowite
        unit_of_measurement: 'tim'
        value_template: "{{ states.vacuum.wowite.attributes.main_brush_left }}"

  - platform: template
    sensors:
      vacuum_side_brush:
        friendly_name: "Sidoborste"
        entity_id: vacuum.wowite
        unit_of_measurement: 'tim'
        value_template: "{{ states.vacuum.wowite.attributes.side_brush_left }}"

  - platform: template
    sensors:
      vacuum_filter:
        friendly_name: "Filter"
        entity_id: vacuum.wowite
        unit_of_measurement: 'tim'
        value_template: "{{ states.vacuum.wowite.attributes.filter_left }}"

  - platform: template
    sensors:
      vacuum_battery:
         friendly_name: 'Batteri'
         value_template: '{{ states.vacuum.wowite.attributes.battery_level}}'
         unit_of_measurement: '%'
         entity_id: vacuum.wowite
         icon_template: '{{ states.vacuum.wowite.attributes.battery_icon }}'

  - platform: template
    sensors:
      vacuum_total_cleaned_area:
        friendly_name: "Städningsyta"
        entity_id: vacuum.wowite
        unit_of_measurement: 'm²'
        value_template: "{{ states.vacuum.wowite.attributes.total_cleaned_area }}"





script:
  vacuum_hallen:
    alias: "Dammsug hallen"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.wowite
          command: app_zoned_clean
          params: [[24121,17825,27471,19175,1]]

  vacuum_matbord:
    alias: "Dammsug runt matbordet"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.wowite
          command: app_zoned_clean
          params: [[18651,22821,21751,25471,1]]


  vacuum_kok:
    alias: "Dammsug köket"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.wowite
          command: app_zoned_clean
          params: [[26237,25192,28537,31792,1]]

  vacuum_vardagsrum:
    alias: "Dammsug vardagsrummet"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.wowite
          command: app_zoned_clean
          params: [[18446,17469,22346,26169,1]]

  vacuum_sovrum:
    alias: "Dammsug sovrummet"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.wowite
          command: app_zoned_clean
          params: [[18464,11177,22514,15477,1]]

  vacuum_albins:
    alias: "Dammsug Albins rum"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.wowite
          command: app_zoned_clean
          params: [[22552,11412,25152,15512,1]]

  vacuum_kontoret:
    alias: "Dammsug kontoret"
    sequence:
      - service: vacuum.send_command
        data:
          entity_id: vacuum.wowite
          command: app_zoned_clean
          params: [[25157,22357,28257,26007,1]]

#  vacuum_lgh:
#    alias: "Hela lägenheten"
#    sequence:
#      - service: vacuum.send_command
#        data:
#          entity_id: vacuum.wowite
#          command: app_zoned_clean
#          params: [[18046,17393,30446,28793,1]]
