sensor:
  - platform: template
    sensors:
      all_lights_check:
        value_template: >-
          {{ states | selectattr('entity_id','in', ['light.albin_fonster','light.albin_hylla','light.bollarna','light.hall_vagglampa','light.hallen_tak','light.koksfonstret','light.kontor_banken','light.kontor_fatolj','light.kontor_hylla','light.kontor_skrivbordet','light.nattlampa','light.sovrum_fonster','light.sovrum_hoger','light.sovrum_vanster','light.vardagsrum_bokhyllan','light.vardagsrum_bord','light.vardagsrum_golvlampa','light.vardagsrum_hoga_hyllan','light.vardagsrum_tv_bank_vanster','light.vardagsrum_tvbank'] )|selectattr('state','eq','on') | list | count }}
        entity_id:
          - light.albin_fonster
          - light.albin_hylla
          - light.bollarna
          - light.hall_vagglampa
          - light.hallen_tak
          - light.koksfonstret
          - light.kontor_banken
          - light.kontor_fatolj
          - light.kontor_hylla
          - light.kontor_skrivbordet
          - light.nattlampa
          - light.sovrum_fonster
          - light.sovrum_hoger
          - light.sovrum_vanster
          - light.vardagsrum_bokhyllan
          - light.vardagsrum_bord
          - light.vardagsrum_golvlampa
          - light.vardagsrum_hoga_hyllan
          - light.vardagsrum_tv_bank_vanster
          - light.vardagsrum_tvbank


      nr_open_doors:
        value_template: >-
          {{ states | selectattr('entity_id','in', ['binary_sensor.backdoor','binary_sensor.franska_balkongen','binary_sensor.frontdoor'] )|selectattr('state','eq','on') | list | count }}
        entity_id:
          - binary_sensor.backdoor
          - binary_sensor.franska_balkongen
          - binary_sensor.kladkammaren
          - sensor.time



#      alarm_contolpanel_varning:
#        value_template: >-
#          {{ states('alarm_control_panel.aarlo_arlo') !=  states('alarm_control_panel.house') }}
#        entity_id:
#          - alarm_control_panel.aarlo_arlo
#          - alarm_control_panel.house
