weather:
  - platform: darksky
    api_key: !secret darksky

airvisual:
    api_key: !secret airvisual
    geographies:
      city: Goeteborg
      state: Västra Götalands län
      country: Sweden


sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_date'
      - 'time_utc'

#######################
#                     #
# SENSORER            #
#                     #
#######################


sensor:
  - platform: darksky
    api_key: !secret darksky
    language: sv
    forecast:
      - 0
      - 1
    scan_interval:
      minutes: 15
    monitored_conditions:
      - summary
      - hourly_summary
      - temperature_low
      - temperature_high
      - precip_probability
      - precip_type
      - apparent_temperature
      - icon

  - platform: moon
  - platform: season

  - platform: yr
    monitored_conditions:
      - symbol
      - dewpointTemperature
      - cloudiness
      - precipitation

  - platform: yr
    name: YR 9h
    forecast: 9
    monitored_conditions:
      - temperature
      - dewpointTemperature
      - precipitation

  - platform: min_max
    name: temp_inne
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.albin_temp
      - sensor.sovrum_temp_pir
      - sensor.vardagsrum_temp
      - sensor.kontoret_temp
      - sensor.hallen_temp

  - platform: min_max
    name: temp_ute
    type: min
    round_digits: 1
    entity_ids:
      - sensor.baksidan_temperature
      - sensor.framsidan_temperature



camera:
  - platform: generic
    name: "Göteborg meteogram"
    still_image_url: https://www.yr.no/sted/Sverige/V%C3%A4stra_G%C3%B6taland/G%C3%B6teborg/meteogram.svg
    content_type: 'image/svg+xml'


automation:
  - alias: 'SMHI Alert'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:  sensor.smhialert
        to: "Alert"
    action:
      - service: notify.alla
        data_template:
          message: >
            {{states.sensor.smhi_event.state}}
