
weather:
  - platform: darksky
    api_key: !secret darksky

airvisual:
    api_key: !secret airvisual
    geographies:
      city: Goeteborg
      state: Västra Götalands län
      country: Sweden

sensor:

  - platform: darksky
    api_key: !secret darksky
    language: sv
    forecast:
      - 0
      - 1
    scan_interval:
      minutes: 15
    monitored_conditions:
      - summary
      - hourly_summary
      - temperature_low
      - temperature_high
      - precip_probability
      - precip_type
      - apparent_temperature
      - icon


  - platform: moon
  - platform: season

  - platform: yr
    monitored_conditions:
      - symbol
      - dewpointTemperature
      - cloudiness
      - precipitation

  - platform: yr
    name: YR 9h
    forecast: 9
    monitored_conditions:
      - temperature
      - dewpointTemperature
      - precipitation



  - platform: min_max
    name: temp_inne
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.albin_temp
      - sensor.sovrum_temp_pir
      - sensor.vardagsrum_temp
      - sensor.kontoret_temp
      - sensor.hallen_temp

  - platform: min_max
    name: temp_ute
    type: min
    round_digits: 1
    entity_ids:
      - sensor.baksidan_temperature
      - sensor.framsidan_temperature

  - platform: smhialert
    district: '007'
    language: 'sv'

  - platform: template
    sensors:
      smhi_event:
        value_template: "{{ states.sensor.smhialert.attributes.messages['007']['msgs'][0]['event'] }}  {{ states.sensor.smhialert.attributes.messages['007']['msgs'][0]['description'] | regex_replace('Intensitet: |När:.*|Var:.*|Kommentar:.*', '') }}{{ states.sensor.smhialert.attributes.messages['007']['msgs'][0]['description'] | regex_replace('När: |Intensitet:.*|Var:.*|Kommentar:.*', '') }}"

  - platform: template
    sensors:
      vader_text:
        value_template:  >-
          {% if states('sensor.temp_ute_filtrerad') == 'unknown' %}
          Kan inte läsa in väderinformation...
          {% else %}
            {% if states('sensor.temp_ute_filtrerad') | float <= 0.0 %}
            Det är {{ states('sensor.temp_ute_filtrerad') | round }}°, känns som {{ states('sensor.dark_sky_apparent_temperature') | round }}°, med
            {{ states('sensor.dark_sky_precip_probability') | round }}% risk för snö {{'\u2744\uFE0F'}}
            {% elif states('sensor.temp_ute_filtrerad') | float > 0.0 %}
            Det är {{ states('sensor.temp_ute_filtrerad') | round }}°, känns som {{ states('sensor.dark_sky_apparent_temperature') | round }}°, med {{ states('sensor.dark_sky_precip_probability') | round }}% risk för regn {%- if states('sensor.dark_sky_precip_probability') | float > 30.0 %}
            {% endif %}
            {% elif states('sensor.temp_ute_filtrerad') | float > 19.0 and
            states('sensor.dark_sky_precip_probability') | float < 5.0 %}
            Det är {{ states('sensor.temp_ute_filtrerad') | round }}°, känns som {{ states('sensor.dark_sky_apparent_temperature') | round }}°, med {{ states('sensor.dark_sky_precip_probability') | round }}% risk för regn
            {% endif %}
          {% endif %}


camera:
  - platform: generic
    name: "Göteborg meteogram"
    still_image_url: https://www.yr.no/sted/Sverige/V%C3%A4stra_G%C3%B6taland/G%C3%B6teborg/meteogram.svg
    content_type: 'image/svg+xml'


automation:
  - alias: 'SMHI Alert'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:  sensor.smhialert
        to: "Alert"
    action:
      - service: notify.alla
        data_template:
          message: >
            {{states.sensor.smhi_event.state}}
