

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_date'
      - 'time_utc'

#  - platform: template
#    sensors:
#      dag:
#        entity_id: sensor.date
#        icon_template: mdi:calendar
#        value_template: >
#          {% set days = ['Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag', 'Söndag'] %}
#          {{ days[now().weekday()] }}

#  - platform: template
#    sensors:
#      datum:
#        icon_template: mdi:calendar
#        value_template: >
#          {% set months = ['Januari', 'Februari', 'Mars', 'April', 'Maj', 'Juni',
#          'Juli', 'Augusti', 'September', 'Oktober', 'November', 'December'] %}
#          {{ strptime(states('sensor.date'), '%Y-%m-%d').day }}
#          {{ months[now().month-1] }}



  - platform: template
    sensors:
      sunset_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting)  | timestamp_custom("%H:%M") }}'
        entity_id: sun.sun

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising)  | timestamp_custom("%H:%M") }}'
        entity_id: sun.sun

      time_at_day:
        entity_id: sensor.time
        value_template: >-
          {% if now().strftime("%H")|int < 5 %}
          natt
          {% elif now().strftime("%H")|int < 10 %}
          morgon
          {% elif now().strftime("%H")|int < 16 %}
          dag
          {% elif now().strftime("%H")|int < 20 %}
          eftermiddag
          {% elif now().strftime("%H")|int < 23 %}
          kväll
          {% else %}
          natt
          {% endif %}
